project:
  name: @project.name@
  version: @project.version@

# Spring Boot configuration
spring:
  profiles:
    active: development

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    ROOT: ERROR
    ru.philit.ufs: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.hazelcast: INFO

# Server configuration
server:
  port: 8087
  session.timeout: 30

# Hazelcast configuration
hazelcast:
  instance:
    host:
    port: 5701
  members:
    addresses:
  group:
    name: ufsbe
    password: ufs
